version: 2.0
rexecutor: &rexecutor
  docker:
    - image: ubuntu:latest 
jobs:
  build:
    <<: *rexecutor
    steps:
      - checkout
      - run: echo build
      - run: ln -s /tmp/workspace .
      - persist_to_workspace:
          root: /tmp/workspace
          paths: 
            - .
  test:
    <<: *rexecutor
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run: echo "$PWD"; ls -a1
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build

