version: 2.0
rexecutor: &rexecutor
  docker:
    - image: alpine:20190809
jobs:
  build:
    <<: *rexecutor
    steps:
      - checkout
      - run: echo build
      - persist_to_workspace:
          root: .
          paths: 
            - .
  test:
    <<: *rexecutor
    steps:
      - attach_workspace:
          at: .
      - run: echo "$PWD"; ls -a1
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build

