version: 2.0
rexecutor: &rexecutor
  docker:
    - image: alpine/latest
    
jobs:
  build:
    *rexecutor
    steps:
      - run: echo build
  test:
    *rexecutor
    steps:
      - run: echo test
workflow:
  build_and_test:
    - build
    - test:
        requires: build

