version: 2.0
rexecutor: &rexecutor
  docker:
    - image: alpine:20190809
jobs:
  build:
    <<: *rexecutor
    steps:
      - checkout
      - run: echo build
  test:
    <<: *rexecutor
    steps:
      - run: echo "$PWD"; ls -a1
workflows:
  version: 2
  build_and_test:
    - build
    - test:
        requires:
          - build

