version: 2.0
jobs:
  build:
    machine
    steps:
      - checkout
      - run: echo build
      - run: ln -s . /tmp/workspace
      - persist_to_workspace:
          root: /tmp/workspace
          paths: 
            - .
  test:
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run: echo "$PWD"; ls -a1
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build

